//! TeX Live + latexmk engine for texrun.
//!
//! [`LatexmkEngine`] implements [`texrun_core::TypesetEngine`] by running the
//! host's latexmk on a prepared workspace (see `texrun-workspace`). It
//! follows the decisions of `docs/security.md` §3:
//!
//! - latexmk is started without a shell, as `latexmk -norc -r <rc> -pdf
//!   -interaction=nonstopmode -halt-on-error -file-line-error
//!   -no-shell-escape -outdir=<absolute output dir> ./<entrypoint file>`,
//!   with the entrypoint's directory as working directory;
//! - the rc is generated by texrun into a temporary directory outside the
//!   workspace (removed after the compile) and makes latexmk run pdflatex /
//!   bibtex / makeindex without a shell, disables kpsewhich and sets every
//!   other command to `NONE` ([`rc`](crate#rc));
//! - the environment is cleared and only an allowlist is set (`PATH` without
//!   relative entries, `HOME=<workspace>/.texrun/home`, kpathsea paranoid
//!   mode, `max_print_line`, `MKTEX*=0`, `LC_ALL=C`);
//! - the entrypoint and output directory names are checked against a
//!   character allowlist;
//! - latexmk runs in its own process group, which is killed with `SIGKILL`
//!   on timeout, cancellation or when an output limit is exceeded, and once
//!   more after latexmk exits (the shared supervisor of `texrun-process`);
//! - output limits: `RLIMIT_FSIZE` per file (Linux), total output directory
//!   size (polled), and the captured stdout / stderr (4 MiB each).
//!
//! The main log is parsed with `texrun-latex-log`; its diagnostics carry
//! workspace-relative file names. BibTeX failures are reported from the
//! `.blg` files latexmk's BibTeX runs wrote into the output directory and
//! from latexmk's console output (e.g. a missing `.bib`, for which latexmk
//! does not run BibTeX at all); see the `bibtex` module for the bounds on
//! what is read. The `.blg` files are not artifacts: their content is in the
//! diagnostics' excerpts.
//!
//! # Platform support
//!
//! Unix only. `RLIMIT_FSIZE` is applied to latexmk with `prlimit(2)` from the
//! parent, because setting it in the child before `exec` needs `unsafe`
//! (`pre_exec`), which this workspace forbids. That call only exists on
//! Linux; on other Unix systems (macOS) the per-file limit is enforced by the
//! periodic output size check only, i.e. with a delay of up to
//! [`Limits::size_check_interval`].
//!
//! # rc
//!
//! See the `rc` module source for the exact content. The rc never contains
//! request data (file names, paths).

#[cfg(not(unix))]
compile_error!("texrun-texlive supports Unix hosts only");

mod bibtex;
mod command;
mod engine;
mod layout;
mod names;
mod process;
mod rc;

pub use engine::{
    DEFAULT_TIMEOUT, ENGINE_NAME, LATEXMK_PROGRAM, LatexmkConfig, LatexmkEngine, LatexmkRun,
    MAX_PARSED_LOG_BYTES,
};
pub use process::{CapturedOutput, Limits};
