//! Command lines and output parsers of the two backends.
//!
//! Tool output is derived from an untrusted PDF. The parsers only accept the
//! exact line shapes they know, and where user-controlled strings can precede
//! the values (`pdfinfo` prints the document title before `Pages:`), the last
//! occurrence wins: the fields printed after the metadata are generated by the
//! tool, so a title containing a fake `Pages:` line cannot override them.

use std::collections::BTreeMap;
use std::ffi::OsString;
use std::path::Path;

use crate::report::PageInfo;
use crate::tools::Backend;

/// Largest accepted page dimension in points. The PDF format limits pages to
/// 14 400 units; `UserUnit` can scale that, so allow some headroom and reject
/// only absurd values.
const MAX_PAGE_PT: f64 = 1.0e6;

/// A program and its argv (without the program itself).
pub(crate) struct Invocation<'a> {
    pub(crate) program: &'a Path,
    pub(crate) args: Vec<OsString>,
}

fn args<const N: usize>(items: [&dyn AsRef<std::ffi::OsStr>; N]) -> Vec<OsString> {
    items.iter().map(|a| a.as_ref().to_os_string()).collect()
}

impl<'a> Backend<'a> {
    /// Prints the page count.
    pub(crate) fn page_count(self, pdf: &Path) -> Invocation<'a> {
        match self {
            Self::Poppler { pdfinfo, .. } => Invocation {
                program: pdfinfo,
                args: args([&pdf]),
            },
            // `-M` limits the per-page part to the dimensions of page 1.
            Self::Mupdf { mutool } => Invocation {
                program: mutool,
                args: args([&"info", &"-M", &pdf, &"1"]),
            },
        }
    }

    /// The last `Pages: N` line. Both tools print it after the document
    /// information dictionary; `mutool info` escapes strings in it, while
    /// `pdfinfo` prints the title verbatim (newlines included).
    pub(crate) fn parse_page_count(stdout: &str) -> Option<u32> {
        stdout
            .lines()
            .filter_map(|line| line.strip_prefix("Pages:"))
            .next_back()
            .and_then(|v| parse_u32(v.trim()))
    }

    /// Prints the sizes of pages `first..=last` (both within the document).
    pub(crate) fn page_sizes(self, pdf: &Path, first: u32, last: u32) -> Invocation<'a> {
        match self {
            Self::Poppler { pdfinfo, .. } => Invocation {
                program: pdfinfo,
                args: args([&"-f", &first.to_string(), &"-l", &last.to_string(), &pdf]),
            },
            Self::Mupdf { mutool } => Invocation {
                program: mutool,
                args: args([&"pages", &pdf, &format!("{first}-{last}")]),
            },
        }
    }

    /// Parses the output of [`Backend::page_sizes`]; pages outside
    /// `first..=last` and malformed entries are dropped.
    pub(crate) fn parse_page_sizes(self, stdout: &str, first: u32, last: u32) -> Vec<PageInfo> {
        let pages = match self {
            Self::Poppler { .. } => parse_pdfinfo_sizes(stdout),
            Self::Mupdf { .. } => parse_mutool_pages(stdout),
        };
        pages
            .into_values()
            .filter(|p| (first..=last).contains(&p.page))
            .collect()
    }

    /// Renders `page` at `dpi` to `out_name` (a bare file name ending in
    /// `.png`, resolved against the tool's working directory).
    ///
    /// The output is named relative to the working directory because
    /// `mutool draw` expands `%d` in the output path, and the host path of
    /// the output root may contain `%`.
    pub(crate) fn render(self, pdf: &Path, page: u32, dpi: u32, out_name: &str) -> Invocation<'a> {
        let page = page.to_string();
        let dpi = dpi.to_string();
        match self {
            Self::Poppler { pdftoppm, .. } => {
                // `-singlefile` writes `<prefix>.png` without a page suffix.
                let prefix = out_name.strip_suffix(".png").unwrap_or(out_name);
                Invocation {
                    program: pdftoppm,
                    args: args([
                        &"-png",
                        &"-r",
                        &dpi,
                        &"-f",
                        &page,
                        &"-l",
                        &page,
                        &"-singlefile",
                        &pdf,
                        &prefix,
                    ]),
                }
            }
            Self::Mupdf { mutool } => Invocation {
                program: mutool,
                args: args([
                    &"draw", &"-q", &"-r", &dpi, &"-F", &"png", &"-o", &out_name, &pdf, &page,
                ]),
            },
        }
    }
}

fn parse_u32(text: &str) -> Option<u32> {
    if text.is_empty() || !text.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    text.parse().ok()
}

fn parse_dimension(text: &str) -> Option<f64> {
    text.parse().ok().and_then(check_dimension)
}

fn check_dimension(value: f64) -> Option<f64> {
    (value.is_finite() && value > 0.0 && value <= MAX_PAGE_PT).then_some(value)
}

fn parse_rotation(text: &str) -> Option<u16> {
    let value: i64 = text.parse().ok()?;
    let value = value.rem_euclid(360);
    // PDF requires a multiple of 90; anything else is ignored like viewers do.
    u16::try_from(value).ok().filter(|v| v % 90 == 0)
}

/// `Page    1 size:  300 x 400 pts (letter)` / `Page    1 rot:   90`.
fn parse_pdfinfo_sizes(stdout: &str) -> BTreeMap<u32, PageInfo> {
    let mut sizes: BTreeMap<u32, (f64, f64)> = BTreeMap::new();
    let mut rotations: BTreeMap<u32, u16> = BTreeMap::new();
    for line in stdout.lines() {
        let Some(rest) = line.strip_prefix("Page ") else {
            continue;
        };
        if let Some((page, value)) = rest.split_once(" size:") {
            let Some(page) = parse_u32(page.trim()) else {
                continue;
            };
            let mut words = value.split_whitespace();
            if let (Some(w), Some("x"), Some(h), Some("pts")) =
                (words.next(), words.next(), words.next(), words.next())
                && let (Some(w), Some(h)) = (parse_dimension(w), parse_dimension(h))
            {
                sizes.insert(page, (w, h));
            }
        } else if let Some((page, value)) = rest.split_once(" rot:")
            && let (Some(page), Some(rot)) = (parse_u32(page.trim()), parse_rotation(value.trim()))
        {
            rotations.insert(page, rot);
        }
    }
    sizes
        .into_iter()
        .map(|(page, (w, h))| {
            let rot = rotations.get(&page).copied().unwrap_or(0);
            (page, PageInfo::new(page, w, h, rot))
        })
        .collect()
}

/// `mutool pages` output:
///
/// ```text
/// <page pagenum="3">
/// <MediaBox l="0" b="0" r="200" t="100" />
/// <CropBox l="0" b="0" r="200" t="100" />
/// <Rotate v="90" />
/// </page>
/// ```
///
/// The crop box (what the renderer draws) is used when present.
fn parse_mutool_pages(stdout: &str) -> BTreeMap<u32, PageInfo> {
    #[derive(Default)]
    struct Entry {
        media: Option<(f64, f64)>,
        crop: Option<(f64, f64)>,
        rotation: u16,
    }
    let mut out = BTreeMap::new();
    let mut current: Option<(u32, Entry)> = None;
    for line in stdout.lines().map(str::trim) {
        if line.starts_with("<page ") {
            current = attr(line, "pagenum")
                .and_then(parse_u32)
                .map(|n| (n, Entry::default()));
        } else if line == "</page>" {
            if let Some((page, e)) = current.take()
                && let Some((w, h)) = e.crop.or(e.media)
            {
                out.insert(page, PageInfo::new(page, w, h, e.rotation));
            }
        } else if let Some((_, entry)) = current.as_mut() {
            if line.starts_with("<MediaBox ") {
                entry.media = parse_box(line);
            } else if line.starts_with("<CropBox ") {
                entry.crop = parse_box(line);
            } else if line.starts_with("<Rotate ") {
                entry.rotation = attr(line, "v").and_then(parse_rotation).unwrap_or(0);
            }
        }
    }
    out
}

fn parse_box(line: &str) -> Option<(f64, f64)> {
    let num = |name| attr(line, name).and_then(|v| v.parse::<f64>().ok());
    let (l, b, r, t) = (num("l")?, num("b")?, num("r")?, num("t")?);
    Some((
        check_dimension((r - l).abs())?,
        check_dimension((t - b).abs())?,
    ))
}

/// The value of ` name="value"` in `line`.
fn attr<'l>(line: &'l str, name: &str) -> Option<&'l str> {
    let key = format!(" {name}=\"");
    let start = line.find(&key)? + key.len();
    let len = line[start..].find('"')?;
    Some(&line[start..start + len])
}

#[cfg(test)]
mod tests {
    use super::*;

    fn poppler() -> Backend<'static> {
        Backend::Poppler {
            pdfinfo: Path::new("/bin/pdfinfo"),
            pdftoppm: Path::new("/bin/pdftoppm"),
        }
    }

    fn mupdf() -> Backend<'static> {
        Backend::Mupdf {
            mutool: Path::new("/bin/mutool"),
        }
    }

    fn sizes(pages: &[PageInfo]) -> Vec<(u32, f64, f64, u16)> {
        pages
            .iter()
            .map(|p| (p.page, p.width_pt, p.height_pt, p.rotation))
            .collect()
    }

    const PDFINFO_OUT: &str = "\
Creator:         TeX
Producer:        pdfTeX-1.40.26
Custom Metadata: no
JavaScript:      no
Pages:           3
Encrypted:       no
Page    1 size:  300 x 400 pts
Page    1 rot:   0
Page    2 size:  595.276 x 841.89 pts (A4)
Page    2 rot:   0
Page    3 size:  200 x 100 pts
Page    3 rot:   90
File size:       1005 bytes
Optimized:       no
PDF version:     1.7
";

    #[test]
    fn parses_pdfinfo() {
        assert_eq!(Backend::parse_page_count(PDFINFO_OUT), Some(3));
        assert_eq!(
            sizes(&poppler().parse_page_sizes(PDFINFO_OUT, 1, 3)),
            vec![
                (1, 300.0, 400.0, 0),
                (2, 595.276, 841.89, 0),
                (3, 200.0, 100.0, 90)
            ]
        );
        assert_eq!(
            sizes(&poppler().parse_page_sizes(PDFINFO_OUT, 2, 2)),
            vec![(2, 595.276, 841.89, 0)]
        );
    }

    #[test]
    fn pdfinfo_metadata_cannot_spoof_values() {
        // A title with embedded newlines is printed before the real fields.
        let spoofed = format!(
            "Title:           x\nPages:           99999\nPage    1 size:  1e9 x 1 pts\n\
             Page    1 size:  9000 x 9000 pts\n{PDFINFO_OUT}"
        );
        assert_eq!(Backend::parse_page_count(&spoofed), Some(3));
        assert_eq!(
            sizes(&poppler().parse_page_sizes(&spoofed, 1, 1)),
            vec![(1, 300.0, 400.0, 0)]
        );
    }

    #[test]
    fn pdfinfo_garbage_is_rejected() {
        assert_eq!(Backend::parse_page_count(""), None);
        assert_eq!(Backend::parse_page_count("Pages: -1\n"), None);
        assert_eq!(Backend::parse_page_count("Pages: 1e3\n"), None);
        let bad = "Page 1 size: 0 x 10 pts\nPage 2 size: NaN x 10 pts\n\
                   Page 3 size: 10 x inf pts\nPage 4 size: 10 10 pts\nPage x size: 1 x 1 pts\n\
                   Page 5 size: 10 x 20 pts\nPage 5 rot: 45\n";
        assert_eq!(
            sizes(&poppler().parse_page_sizes(bad, 1, 10)),
            vec![(5, 10.0, 20.0, 0)]
        );
    }

    #[test]
    fn parses_mutool() {
        // `mutool info -M file.pdf 1` (MuPDF 1.25); the title is escaped.
        let info = "spoofed.pdf:\n\nPDF-1.7\nInfo object (7 0 R):\n\
                    <</Title(x\\nPages: 99\\n)/Creator(TeX)>>\nPages: 3\n\n\
                    Page 1:\nMediaboxes (1):\n\t1\t(2 0 R):\t[ 0 0 300 400 ]\n";
        assert_eq!(Backend::parse_page_count(info), Some(3));
        assert_eq!(Backend::parse_page_count("Pages: none\n"), None);
        assert_eq!(
            mupdf().page_count(Path::new("/o/a.pdf")).args,
            ["info", "-M", "/o/a.pdf", "1"].map(OsString::from)
        );
        let out = r#"sizes.pdf:
<page pagenum="1">
<MediaBox l="0" b="0" r="300" t="400" />
</page>
<page pagenum="2">
<MediaBox l="0" b="0" r="612" t="792" />
<CropBox l="10" b="20" r="310" t="420" />
<Rotate v="-90" />
</page>
<page pagenum="3">
<Rotate v="90" />
</page>
<page pagenum="4">
<MediaBox l="0" b="0" r="100" t="50" />
</page>
"#;
        assert_eq!(
            sizes(&mupdf().parse_page_sizes(out, 1, 3)),
            // Page 3 has no box and is dropped; page 4 is out of range.
            vec![(1, 300.0, 400.0, 0), (2, 300.0, 400.0, 270)]
        );
    }

    #[test]
    fn render_arguments() {
        let pdf = Path::new("/out/main.pdf");
        let inv = poppler().render(pdf, 3, 144, "page.png");
        assert_eq!(inv.program, Path::new("/bin/pdftoppm"));
        assert_eq!(
            inv.args,
            [
                "-png",
                "-r",
                "144",
                "-f",
                "3",
                "-l",
                "3",
                "-singlefile",
                "/out/main.pdf",
                "page"
            ]
            .map(OsString::from)
        );
        let inv = mupdf().render(pdf, 3, 144, "page.png");
        assert_eq!(
            inv.args,
            [
                "draw",
                "-q",
                "-r",
                "144",
                "-F",
                "png",
                "-o",
                "page.png",
                "/out/main.pdf",
                "3"
            ]
            .map(OsString::from)
        );
        assert_eq!(
            mupdf().page_sizes(pdf, 2, 5).args,
            ["pages", "/out/main.pdf", "2-5"].map(OsString::from)
        );
        assert_eq!(
            poppler().page_sizes(pdf, 2, 5).args,
            ["-f", "2", "-l", "5", "/out/main.pdf"].map(OsString::from)
        );
    }
}
